services:
  finance-api:
    build:
      context: .
      dockerfile: Dockerfile

    image: finance-api:1.0.0

    container_name: finance-api

    restart: unless-stopped

    env_file:
      ../compose/.env

    environment:
      SPRING_PROFILES_ACTIVE: prod

    ports:
      - "8080:8080"